import axios from 'axios'
import Head from 'next/head'
import Classlist from '../components/Classlist'
import Featured from '../components/Featured'

export default function Home({pizzaList}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Featured/>
      <Classlist pizzaList={pizzaList}/>
    
    </>
  )
}

export const getServerSideProps = async () => {
  const res  = await axios.get("http://localhost:3005/api/products");
  return{
    props: {
      pizzaList: res.data,  
    },
  };
}