import axios from 'axios'
import Head from 'next/head'
import { useState } from 'react'
import { Add } from '../components/Add'
import { AddButton } from '../components/AddButton'
import Classlist from '../components/Classlist'
import Featured from '../components/Featured'

export default function Home({pizzaList, admin, host}) {
 
  const [close, setClose] = useState(true);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Featured/>
      {
        admin && (
          <AddButton setClose={setClose}/>
        )
      }

      <Classlist pizzaList={pizzaList}/>
      
      {
        !close && (
          <Add setClose={setClose}/>
        )
      }

    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const { req, query, res, asPath, pathname } = ctx;

  const myCookie = req?.cookies || '';
  let admin = false;

  if(myCookie.token === process.env.TOKEN){
    admin = true;
  }
  
  let host = '';
  if (req) {
    host = req.headers.host // will give you localhost:3005
  }

  console.log(host)

  const resq  = await axios.get(`http://${host}/api/products`);
  return{
    props: {
      pizzaList: resq.data || '',  
      admin,
      host, 
    },
  };
}